// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Script, console} from "forge-std/Script.sol";

import {DeploymentsMainnet} from "src/config/manifest.mainnet.sol";
import {DeploymentsSepolia} from "src/config/manifest.sepolia.sol";
import {DeploymentAddressesMainnet, DeploymentAddressesSepolia} from "src/config/DeploymentAddresses.sol";

/// @title ExportDeployments
/// @notice Renders `deployments.{mainnet,sepolia}.md` from the Solidity manifests.
/// @dev Run with `just export-deployments` (or `forge script ExportDeployments`). The
///      output `.md` files are generated artifacts — never edit them by hand. CI runs
///      this script and fails if the result differs from what is committed.
contract ExportDeployments is Script {
    string private constant DO_NOT_EDIT_MAINNET =
        "<!-- generated by `just export-deployments` from `manifest.mainnet.sol` - do not hand-edit -->\n\n";
    string private constant DO_NOT_EDIT_SEPOLIA =
        "<!-- generated by `just export-deployments` from `manifest.sepolia.sol` - do not hand-edit -->\n\n";

    function run() public {
        string memory mainnetMd = _renderMainnet();
        string memory sepoliaMd = _renderSepolia();

        vm.writeFile("deployments.mainnet.md", mainnetMd);
        vm.writeFile("deployments.sepolia.md", sepoliaMd);

        console.log("Wrote deployments.mainnet.md (%d bytes)", bytes(mainnetMd).length);
        console.log("Wrote deployments.sepolia.md (%d bytes)", bytes(sepoliaMd).length);
    }

    // ---------------------------------------------------------------- Mainnet

    function _renderMainnet() internal pure returns (string memory s) {
        s = string.concat(DO_NOT_EDIT_MAINNET, "# Mainnet deployments\n\n");

        s = string.concat(s, "## Livo\n\n", _tableHeader("Contract"));
        s = string.concat(s, _row("LivoLaunchpad", DeploymentsMainnet.LAUNCHPAD));
        s = string.concat(s, _row("ConstantProductBondingCurve", DeploymentsMainnet.BONDING_CURVE));
        s = string.concat(s, _row("LivoGraduatorUniswapV2", DeploymentsMainnet.GRADUATOR_UNIV2));
        s = string.concat(s, _row("LivoGraduatorUniswapV4", DeploymentsMainnet.GRADUATOR_UNIV4));
        s = string.concat(s, _row("LivoGraduatorUniswapV4 (0.5% hook)", DeploymentsMainnet.GRADUATOR_UNIV4_0P5));
        s = string.concat(s, _row("LivoMasterFeeHandler", DeploymentsMainnet.MASTER_FEE_HANDLER));
        s = string.concat(s, _row("LivoSwapHook", DeploymentsMainnet.SWAP_HOOK));
        s = string.concat(s, _row("LivoSwapHook (0.5%)", DeploymentsMainnet.SWAP_HOOK_0P5));
        s = string.concat(s, _row("LivoQuoter", DeploymentsMainnet.QUOTER));
        s = string.concat(s, _row("LivoToken (impl)", DeploymentsMainnet.TOKEN_IMPL));
        s = string.concat(s, _row("LivoTaxableTokenUniV4 (impl)", DeploymentsMainnet.TAXABLE_TOKEN_IMPL));
        s = string.concat(s, _row("LivoTaxableTokenUniV2 (impl)", DeploymentsMainnet.TAXABLE_TOKEN_V2_IMPL));
        s = string.concat(s, _row("LivoFactoryUniV2Unified (proxy)", DeploymentsMainnet.FACTORY_UNIV2_UNIFIED));
        s = string.concat(s, _row("LivoFactoryUniV2Unified (impl)", DeploymentsMainnet.FACTORY_UNIV2_UNIFIED_IMPL));
        s = string.concat(s, _row("LivoFactoryUniV4Unified (proxy)", DeploymentsMainnet.FACTORY_UNIV4_UNIFIED));
        s = string.concat(s, _row("LivoFactoryUniV4Unified (impl)", DeploymentsMainnet.FACTORY_UNIV4_UNIFIED_IMPL));
        s = string.concat(s, _row("LivoCreatorVaultFactory (proxy)", DeploymentsMainnet.CREATOR_VAULT_FACTORY));
        s = string.concat(s, _row("LivoCreatorVaultFactory (impl)", DeploymentsMainnet.CREATOR_VAULT_FACTORY_IMPL));
        s = string.concat(s, _row("LivoCreatorVault (impl)", DeploymentsMainnet.CREATOR_VAULT_IMPL));
        s = string.concat(s, _row("Creator-vault curve 5%", DeploymentsMainnet.VAULT_CURVE_5));
        s = string.concat(s, _row("Creator-vault curve 10%", DeploymentsMainnet.VAULT_CURVE_10));
        s = string.concat(s, _row("Creator-vault curve 15%", DeploymentsMainnet.VAULT_CURVE_15));
        s = string.concat(s, _row("Creator-vault curve 20%", DeploymentsMainnet.VAULT_CURVE_20));
        s = string.concat(s, _row("Creator-vault curve 25%", DeploymentsMainnet.VAULT_CURVE_25));
        s = string.concat(s, _row("Creator-vault curve 30%", DeploymentsMainnet.VAULT_CURVE_30));
        s = string.concat(s, _row("LivoGraduatorUniV4 THIN", DeploymentsMainnet.GRADUATOR_UNIV4_THIN));
        s = string.concat(s, _row("LivoGraduatorUniV4 THIN (0.5%)", DeploymentsMainnet.GRADUATOR_UNIV4_THIN_0P5));
        s = string.concat(s, _row("LivoGraduatorUniV4 THICK", DeploymentsMainnet.GRADUATOR_UNIV4_THICK));
        s = string.concat(s, _row("LivoGraduatorUniV4 THICK (0.5%)", DeploymentsMainnet.GRADUATOR_UNIV4_THICK_0P5));
        s = string.concat(s, _row("THIN-tier curve base", DeploymentsMainnet.THIN_CURVE_BASE));
        s = string.concat(s, _row("THIN-tier curve 5%", DeploymentsMainnet.THIN_VAULT_CURVE_5));
        s = string.concat(s, _row("THIN-tier curve 10%", DeploymentsMainnet.THIN_VAULT_CURVE_10));
        s = string.concat(s, _row("THIN-tier curve 15%", DeploymentsMainnet.THIN_VAULT_CURVE_15));
        s = string.concat(s, _row("THIN-tier curve 20%", DeploymentsMainnet.THIN_VAULT_CURVE_20));
        s = string.concat(s, _row("THIN-tier curve 25%", DeploymentsMainnet.THIN_VAULT_CURVE_25));
        s = string.concat(s, _row("THIN-tier curve 30%", DeploymentsMainnet.THIN_VAULT_CURVE_30));
        s = string.concat(s, _row("THICK-tier curve base", DeploymentsMainnet.THICK_CURVE_BASE));
        s = string.concat(s, _row("THICK-tier curve 5%", DeploymentsMainnet.THICK_VAULT_CURVE_5));
        s = string.concat(s, _row("THICK-tier curve 10%", DeploymentsMainnet.THICK_VAULT_CURVE_10));
        s = string.concat(s, _row("THICK-tier curve 15%", DeploymentsMainnet.THICK_VAULT_CURVE_15));
        s = string.concat(s, _row("THICK-tier curve 20%", DeploymentsMainnet.THICK_VAULT_CURVE_20));
        s = string.concat(s, _row("THICK-tier curve 25%", DeploymentsMainnet.THICK_VAULT_CURVE_25));
        s = string.concat(s, _row("THICK-tier curve 30%", DeploymentsMainnet.THICK_VAULT_CURVE_30));

        s = string.concat(s, "\n## Accounts\n\n", _tableHeader("Name"));
        s = string.concat(s, _row("Livo Deployer", DeploymentsMainnet.LIVO_DEV));
        s = string.concat(s, _row("Livo Treasury", DeploymentAddressesMainnet.LIVO_TREASURY));
        s = string.concat(s, _row("Livo Token Deployer", DeploymentsMainnet.LIVO_TOKEN_DEPLOYER));

        s = string.concat(s, "\n## Integrations\n\n", _tableHeader("Name"));
        s = string.concat(s, _row("WETH", DeploymentAddressesMainnet.WETH));
        s = string.concat(s, _row("Uniswap V2 router", DeploymentAddressesMainnet.UNIV2_ROUTER));
        s = string.concat(s, _row("Uniswap V2 factory", DeploymentAddressesMainnet.UNIV2_FACTORY));
        s = string.concat(s, _row("Uniswap V4 Pool Manager", DeploymentAddressesMainnet.UNIV4_POOL_MANAGER));
        s = string.concat(s, _row("Uniswap V4 Position Manager", DeploymentAddressesMainnet.UNIV4_POSITION_MANAGER));
        s = string.concat(s, _row("Uniswap V4 Universal router", DeploymentAddressesMainnet.UNIV4_UNIVERSAL_ROUTER));
        s = string.concat(s, _row("Permit2", DeploymentAddressesMainnet.PERMIT2));
    }

    // ---------------------------------------------------------------- Sepolia

    function _renderSepolia() internal pure returns (string memory s) {
        s = string.concat(DO_NOT_EDIT_SEPOLIA, "# Sepolia deployments\n\n");

        s = string.concat(s, "## Livo\n\n", _tableHeader("Contract"));
        s = string.concat(s, _row("LivoLaunchpad", DeploymentsSepolia.LAUNCHPAD));
        s = string.concat(s, _row("ConstantProductBondingCurve", DeploymentsSepolia.BONDING_CURVE));
        s = string.concat(s, _row("LivoGraduatorUniswapV2", DeploymentsSepolia.GRADUATOR_UNIV2));
        s = string.concat(s, _row("LivoGraduatorUniswapV4", DeploymentsSepolia.GRADUATOR_UNIV4));
        s = string.concat(s, _row("LivoGraduatorUniswapV4 (0.5% hook)", DeploymentsSepolia.GRADUATOR_UNIV4_0P5));
        s = string.concat(s, _row("LivoMasterFeeHandler", DeploymentsSepolia.MASTER_FEE_HANDLER));
        s = string.concat(s, _row("LivoSwapHook", DeploymentsSepolia.SWAP_HOOK));
        s = string.concat(s, _row("LivoSwapHook (0.5%)", DeploymentsSepolia.SWAP_HOOK_0P5));
        s = string.concat(s, _row("LivoQuoter", DeploymentsSepolia.QUOTER));
        s = string.concat(s, _row("LivoToken (impl)", DeploymentsSepolia.TOKEN_IMPL));
        s = string.concat(s, _row("LivoTaxableTokenUniV4 (impl)", DeploymentsSepolia.TAXABLE_TOKEN_IMPL));
        s = string.concat(s, _row("LivoTaxableTokenUniV2 (impl)", DeploymentsSepolia.TAXABLE_TOKEN_V2_IMPL));
        s = string.concat(s, _row("LivoFactoryUniV2Unified (proxy)", DeploymentsSepolia.FACTORY_UNIV2_UNIFIED));
        s = string.concat(s, _row("LivoFactoryUniV2Unified (impl)", DeploymentsSepolia.FACTORY_UNIV2_UNIFIED_IMPL));
        s = string.concat(s, _row("LivoFactoryUniV4Unified (proxy)", DeploymentsSepolia.FACTORY_UNIV4_UNIFIED));
        s = string.concat(s, _row("LivoFactoryUniV4Unified (impl)", DeploymentsSepolia.FACTORY_UNIV4_UNIFIED_IMPL));
        s = string.concat(s, _row("LivoCreatorVaultFactory (proxy)", DeploymentsSepolia.CREATOR_VAULT_FACTORY));
        s = string.concat(s, _row("LivoCreatorVaultFactory (impl)", DeploymentsSepolia.CREATOR_VAULT_FACTORY_IMPL));
        s = string.concat(s, _row("LivoCreatorVault (impl)", DeploymentsSepolia.CREATOR_VAULT_IMPL));
        s = string.concat(s, _row("Creator-vault curve 5%", DeploymentsSepolia.VAULT_CURVE_5));
        s = string.concat(s, _row("Creator-vault curve 10%", DeploymentsSepolia.VAULT_CURVE_10));
        s = string.concat(s, _row("Creator-vault curve 15%", DeploymentsSepolia.VAULT_CURVE_15));
        s = string.concat(s, _row("Creator-vault curve 20%", DeploymentsSepolia.VAULT_CURVE_20));
        s = string.concat(s, _row("Creator-vault curve 25%", DeploymentsSepolia.VAULT_CURVE_25));
        s = string.concat(s, _row("Creator-vault curve 30%", DeploymentsSepolia.VAULT_CURVE_30));
        s = string.concat(s, _row("LivoGraduatorUniV4 THIN", DeploymentsSepolia.GRADUATOR_UNIV4_THIN));
        s = string.concat(s, _row("LivoGraduatorUniV4 THIN (0.5%)", DeploymentsSepolia.GRADUATOR_UNIV4_THIN_0P5));
        s = string.concat(s, _row("LivoGraduatorUniV4 THICK", DeploymentsSepolia.GRADUATOR_UNIV4_THICK));
        s = string.concat(s, _row("LivoGraduatorUniV4 THICK (0.5%)", DeploymentsSepolia.GRADUATOR_UNIV4_THICK_0P5));
        s = string.concat(s, _row("THIN-tier curve base", DeploymentsSepolia.THIN_CURVE_BASE));
        s = string.concat(s, _row("THIN-tier curve 5%", DeploymentsSepolia.THIN_VAULT_CURVE_5));
        s = string.concat(s, _row("THIN-tier curve 10%", DeploymentsSepolia.THIN_VAULT_CURVE_10));
        s = string.concat(s, _row("THIN-tier curve 15%", DeploymentsSepolia.THIN_VAULT_CURVE_15));
        s = string.concat(s, _row("THIN-tier curve 20%", DeploymentsSepolia.THIN_VAULT_CURVE_20));
        s = string.concat(s, _row("THIN-tier curve 25%", DeploymentsSepolia.THIN_VAULT_CURVE_25));
        s = string.concat(s, _row("THIN-tier curve 30%", DeploymentsSepolia.THIN_VAULT_CURVE_30));
        s = string.concat(s, _row("THICK-tier curve base", DeploymentsSepolia.THICK_CURVE_BASE));
        s = string.concat(s, _row("THICK-tier curve 5%", DeploymentsSepolia.THICK_VAULT_CURVE_5));
        s = string.concat(s, _row("THICK-tier curve 10%", DeploymentsSepolia.THICK_VAULT_CURVE_10));
        s = string.concat(s, _row("THICK-tier curve 15%", DeploymentsSepolia.THICK_VAULT_CURVE_15));
        s = string.concat(s, _row("THICK-tier curve 20%", DeploymentsSepolia.THICK_VAULT_CURVE_20));
        s = string.concat(s, _row("THICK-tier curve 25%", DeploymentsSepolia.THICK_VAULT_CURVE_25));
        s = string.concat(s, _row("THICK-tier curve 30%", DeploymentsSepolia.THICK_VAULT_CURVE_30));

        s = string.concat(s, "\n## Accounts\n\n", _tableHeader("Name"));
        s = string.concat(s, _row("Livo Dev", DeploymentsSepolia.LIVO_DEV));
        s = string.concat(s, _row("Livo Token Deployer", DeploymentsSepolia.LIVO_TOKEN_DEPLOYER));

        s = string.concat(s, "\n## Integrations\n\n", _tableHeader("Name"));
        s = string.concat(s, _row("WETH (Uniswap V2)", DeploymentAddressesSepolia.WETH));
        s = string.concat(s, _row("Uniswap V2 router", DeploymentAddressesSepolia.UNIV2_ROUTER));
        s = string.concat(s, _row("Uniswap V2 factory", DeploymentAddressesSepolia.UNIV2_FACTORY));
        s = string.concat(s, _row("Uniswap V4 Pool Manager", DeploymentAddressesSepolia.UNIV4_POOL_MANAGER));
        s = string.concat(s, _row("Uniswap V4 Position Manager", DeploymentAddressesSepolia.UNIV4_POSITION_MANAGER));
        s = string.concat(s, _row("Uniswap V4 Universal router", DeploymentAddressesSepolia.UNIV4_UNIVERSAL_ROUTER));
        s = string.concat(s, _row("Permit2", DeploymentAddressesSepolia.PERMIT2));
    }

    // ---------------------------------------------------------------- Helpers

    /// @dev Inner column widths (content + padding, excluding the surrounding `| ` and ` |`).
    ///      Backticked addresses are exactly 44 chars (`0x` + 40 hex + 2 backticks), which drives the
    ///      width; every deployment name is shorter than that, so 44 fits both columns.
    uint256 private constant COL1_WIDTH = 44;
    uint256 private constant COL2_WIDTH = 44;

    function _tableHeader(string memory firstCol) private pure returns (string memory) {
        return string.concat(
            "| ",
            _padRight(firstCol, COL1_WIDTH),
            " | ",
            _padRight("Address", COL2_WIDTH),
            " |\n",
            "| ",
            _repeat(0x2d, COL1_WIDTH),
            " | ",
            _repeat(0x2d, COL2_WIDTH),
            " |\n"
        );
    }

    function _row(string memory name, address a) private pure returns (string memory) {
        string memory addr = (a == address(0)) ? "_(not deployed)_" : string.concat("`", vm.toString(a), "`");
        return string.concat("| ", _padRight(name, COL1_WIDTH), " | ", _padRight(addr, COL2_WIDTH), " |\n");
    }

    function _padRight(string memory s, uint256 width) private pure returns (string memory) {
        bytes memory original = bytes(s);
        if (original.length >= width) return s;
        bytes memory result = new bytes(width);
        for (uint256 i = 0; i < original.length; i++) {
            result[i] = original[i];
        }
        for (uint256 i = original.length; i < width; i++) {
            result[i] = 0x20;
        }
        return string(result);
    }

    function _repeat(bytes1 ch, uint256 n) private pure returns (string memory) {
        bytes memory result = new bytes(n);
        for (uint256 i = 0; i < n; i++) {
            result[i] = ch;
        }
        return string(result);
    }
}
