// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Script, console} from "forge-std/Script.sol";

import {DeploymentsMainnet} from "src/config/deployments.mainnet.sol";
import {DeploymentsSepolia} from "src/config/deployments.sepolia.sol";
import {DeploymentAddressesMainnet, DeploymentAddressesSepolia} from "src/config/DeploymentAddresses.sol";

/// @title ExportDeployments
/// @notice Renders `deployments.{mainnet,sepolia}.md` from the Solidity manifests.
/// @dev Run with `just export-deployments` (or `forge script ExportDeployments`). The
///      output `.md` files are generated artifacts — never edit them by hand. CI runs
///      this script and fails if the result differs from what is committed.
contract ExportDeployments is Script {
    string private constant DO_NOT_EDIT_MAINNET =
        "<!-- generated by `just export-deployments` from `deployments.mainnet.sol` - do not hand-edit -->\n\n";
    string private constant DO_NOT_EDIT_SEPOLIA =
        "<!-- generated by `just export-deployments` from `deployments.sepolia.sol` - do not hand-edit -->\n\n";

    function run() public {
        string memory mainnetMd = _renderMainnet();
        string memory sepoliaMd = _renderSepolia();

        vm.writeFile("deployments.mainnet.md", mainnetMd);
        vm.writeFile("deployments.sepolia.md", sepoliaMd);

        console.log("Wrote deployments.mainnet.md (%d bytes)", bytes(mainnetMd).length);
        console.log("Wrote deployments.sepolia.md (%d bytes)", bytes(sepoliaMd).length);
    }

    // ---------------------------------------------------------------- Mainnet

    function _renderMainnet() internal pure returns (string memory s) {
        s = string.concat(DO_NOT_EDIT_MAINNET, "# Mainnet deployments\n\n");

        s = string.concat(s, "## Livo\n\n", _tableHeader("Contract"));
        s = string.concat(s, _row("LivoLaunchpad", DeploymentsMainnet.LAUNCHPAD));
        s = string.concat(s, _row("ConstantProductBondingCurve", DeploymentsMainnet.BONDING_CURVE));
        s = string.concat(s, _row("LivoFeeHandler", DeploymentsMainnet.FEE_HANDLER));
        s = string.concat(s, _row("LivoSwapHook", DeploymentsMainnet.SWAP_HOOK));
        s = string.concat(s, _row("LivoGraduatorUniswapV2", DeploymentsMainnet.GRADUATOR_UNIV2));
        s = string.concat(s, _row("LivoGraduatorUniswapV4", DeploymentsMainnet.GRADUATOR_UNIV4));
        s = string.concat(s, _row("LivoFeeSplitter (impl)", DeploymentsMainnet.FEE_SPLITTER_IMPL));
        s = string.concat(s, _row("LivoQuoter", DeploymentsMainnet.QUOTER));
        s = string.concat(s, _row("LivoToken (impl)", DeploymentsMainnet.TOKEN_IMPL));
        s = string.concat(s, _row("LivoTaxableTokenUniV4 (impl)", DeploymentsMainnet.TAXABLE_TOKEN_IMPL));
        s = string.concat(s, _row("LivoTokenSniperProtected (impl)", DeploymentsMainnet.TOKEN_SNIPER_PROTECTED_IMPL));
        s = string.concat(
            s,
            _row("LivoTaxableTokenUniV4SniperProtected (impl)", DeploymentsMainnet.TAXABLE_TOKEN_SNIPER_PROTECTED_IMPL)
        );
        s = string.concat(s, _row("LivoFactoryUniV2", DeploymentsMainnet.FACTORY_UNIV2));
        s = string.concat(s, _row("LivoFactoryUniV4", DeploymentsMainnet.FACTORY_UNIV4));
        s = string.concat(s, _row("LivoFactoryTaxToken", DeploymentsMainnet.FACTORY_TAX_TOKEN));
        s = string.concat(s, _row("LivoFactoryUniV2SniperProtected", DeploymentsMainnet.FACTORY_UNIV2_SNIPER_PROTECTED));
        s = string.concat(s, _row("LivoFactoryUniV4SniperProtected", DeploymentsMainnet.FACTORY_UNIV4_SNIPER_PROTECTED));
        s = string.concat(
            s, _row("LivoFactoryTaxTokenSniperProtected", DeploymentsMainnet.FACTORY_TAX_TOKEN_SNIPER_PROTECTED)
        );

        s = string.concat(s, "\n## Accounts\n\n", _tableHeader("Name"));
        s = string.concat(s, _row("Livo Deployer", DeploymentsMainnet.LIVO_DEV));
        s = string.concat(s, _row("Livo Treasury", DeploymentAddressesMainnet.LIVO_TREASURY));
        s = string.concat(s, _row("Livo Token Deployer", DeploymentsMainnet.LIVO_TOKEN_DEPLOYER));

        s = string.concat(s, "\n## Integrations\n\n", _tableHeader("Name"));
        s = string.concat(s, _row("WETH", DeploymentAddressesMainnet.WETH));
        s = string.concat(s, _row("Uniswap V2 router", DeploymentAddressesMainnet.UNIV2_ROUTER));
        s = string.concat(s, _row("Uniswap V2 factory", DeploymentAddressesMainnet.UNIV2_FACTORY));
        s = string.concat(s, _row("Uniswap V4 Pool Manager", DeploymentAddressesMainnet.UNIV4_POOL_MANAGER));
        s = string.concat(s, _row("Uniswap V4 Position Manager", DeploymentAddressesMainnet.UNIV4_POSITION_MANAGER));
        s = string.concat(s, _row("Uniswap V4 Universal router", DeploymentAddressesMainnet.UNIV4_UNIVERSAL_ROUTER));
        s = string.concat(s, _row("Permit2", DeploymentAddressesMainnet.PERMIT2));
    }

    // ---------------------------------------------------------------- Sepolia

    function _renderSepolia() internal pure returns (string memory s) {
        s = string.concat(DO_NOT_EDIT_SEPOLIA, "# Sepolia deployments\n\n");

        s = string.concat(s, "## Livo\n\n", _tableHeader("Contract"));
        s = string.concat(s, _row("LivoLaunchpad", DeploymentsSepolia.LAUNCHPAD));
        s = string.concat(s, _row("ConstantProductBondingCurve", DeploymentsSepolia.BONDING_CURVE));
        s = string.concat(s, _row("LivoFeeHandler", DeploymentsSepolia.FEE_HANDLER));
        s = string.concat(s, _row("LivoSwapHook", DeploymentsSepolia.SWAP_HOOK));
        s = string.concat(s, _row("LivoGraduatorUniswapV2", DeploymentsSepolia.GRADUATOR_UNIV2));
        s = string.concat(s, _row("LivoGraduatorUniswapV4", DeploymentsSepolia.GRADUATOR_UNIV4));
        s = string.concat(s, _row("LivoFeeSplitter (impl)", DeploymentsSepolia.FEE_SPLITTER_IMPL));
        s = string.concat(s, _row("LivoQuoter", DeploymentsSepolia.QUOTER));
        s = string.concat(s, _row("LivoToken (impl)", DeploymentsSepolia.TOKEN_IMPL));
        s = string.concat(s, _row("LivoTaxableTokenUniV4 (impl)", DeploymentsSepolia.TAXABLE_TOKEN_IMPL));
        s = string.concat(s, _row("LivoTokenSniperProtected (impl)", DeploymentsSepolia.TOKEN_SNIPER_PROTECTED_IMPL));
        s = string.concat(
            s,
            _row("LivoTaxableTokenUniV4SniperProtected (impl)", DeploymentsSepolia.TAXABLE_TOKEN_SNIPER_PROTECTED_IMPL)
        );
        s = string.concat(s, _row("LivoFactoryUniV2", DeploymentsSepolia.FACTORY_UNIV2));
        s = string.concat(s, _row("LivoFactoryUniV4", DeploymentsSepolia.FACTORY_UNIV4));
        s = string.concat(s, _row("LivoFactoryTaxToken", DeploymentsSepolia.FACTORY_TAX_TOKEN));
        s = string.concat(s, _row("LivoFactoryUniV2SniperProtected", DeploymentsSepolia.FACTORY_UNIV2_SNIPER_PROTECTED));
        s = string.concat(s, _row("LivoFactoryUniV4SniperProtected", DeploymentsSepolia.FACTORY_UNIV4_SNIPER_PROTECTED));
        s = string.concat(
            s, _row("LivoFactoryTaxTokenSniperProtected", DeploymentsSepolia.FACTORY_TAX_TOKEN_SNIPER_PROTECTED)
        );

        s = string.concat(s, "\n## Accounts\n\n", _tableHeader("Name"));
        s = string.concat(s, _row("Livo Dev", DeploymentsSepolia.LIVO_DEV));
        s = string.concat(s, _row("Livo Token Deployer", DeploymentsSepolia.LIVO_TOKEN_DEPLOYER));

        s = string.concat(s, "\n## Integrations\n\n", _tableHeader("Name"));
        s = string.concat(s, _row("WETH (Uniswap V2)", DeploymentAddressesSepolia.WETH));
        s = string.concat(s, _row("Uniswap V2 router", DeploymentAddressesSepolia.UNIV2_ROUTER));
        s = string.concat(s, _row("Uniswap V2 factory", DeploymentAddressesSepolia.UNIV2_FACTORY));
        s = string.concat(s, _row("Uniswap V4 Pool Manager", DeploymentAddressesSepolia.UNIV4_POOL_MANAGER));
        s = string.concat(s, _row("Uniswap V4 Position Manager", DeploymentAddressesSepolia.UNIV4_POSITION_MANAGER));
        s = string.concat(s, _row("Uniswap V4 Universal router", DeploymentAddressesSepolia.UNIV4_UNIVERSAL_ROUTER));
        s = string.concat(s, _row("Permit2", DeploymentAddressesSepolia.PERMIT2));
    }

    // ---------------------------------------------------------------- Helpers

    /// @dev Inner column widths (content + padding, excluding the surrounding `| ` and ` |`).
    ///      Longest name today is `LivoTaxableTokenUniV4SniperProtected (impl)` = 43 chars,
    ///      so 44 leaves a 1-char buffer. Backticked addresses are exactly 44 chars
    ///      (`0x` + 40 hex + 2 backticks), so the same width fits the address column too.
    uint256 private constant COL1_WIDTH = 44;
    uint256 private constant COL2_WIDTH = 44;

    function _tableHeader(string memory firstCol) private pure returns (string memory) {
        return string.concat(
            "| ",
            _padRight(firstCol, COL1_WIDTH),
            " | ",
            _padRight("Address", COL2_WIDTH),
            " |\n",
            "| ",
            _repeat(0x2d, COL1_WIDTH),
            " | ",
            _repeat(0x2d, COL2_WIDTH),
            " |\n"
        );
    }

    function _row(string memory name, address a) private pure returns (string memory) {
        string memory addr = (a == address(0)) ? "_(not deployed)_" : string.concat("`", vm.toString(a), "`");
        return string.concat("| ", _padRight(name, COL1_WIDTH), " | ", _padRight(addr, COL2_WIDTH), " |\n");
    }

    function _padRight(string memory s, uint256 width) private pure returns (string memory) {
        bytes memory original = bytes(s);
        if (original.length >= width) return s;
        bytes memory result = new bytes(width);
        for (uint256 i = 0; i < original.length; i++) {
            result[i] = original[i];
        }
        for (uint256 i = original.length; i < width; i++) {
            result[i] = 0x20;
        }
        return string(result);
    }

    function _repeat(bytes1 ch, uint256 n) private pure returns (string memory) {
        bytes memory result = new bytes(n);
        for (uint256 i = 0; i < n; i++) {
            result[i] = ch;
        }
        return string(result);
    }
}
